<a href="https://colab.research.google.com/github/Suman18-bit/Deep-Learning/blob/main/Normalizing_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import tensorflow as tf

In [37]:
tensor = tf.random.uniform(shape=(4,4),minval=0,maxval=10,dtype=tf.int32)

In [38]:
print("The Tensor \n",tensor.numpy())

The Tensor 
 [[9 0 2 4]
 [9 3 7 6]
 [7 8 1 0]
 [6 9 4 9]]


In [39]:
normalized_tensor = tf.cast(tensor, tf.float32) / 8

In [40]:
print("The Normalized Tensor \n",normalized_tensor.numpy())

The Normalized Tensor 
 [[1.125 0.    0.25  0.5  ]
 [1.125 0.375 0.875 0.75 ]
 [0.875 1.    0.125 0.   ]
 [0.75  1.125 0.5   1.125]]


In [41]:
print("The MEAN of the Normalized Tensor is :-",tf.reduce_mean(normalized_tensor).numpy())

The MEAN of the Normalized Tensor is :- 0.65625


In [42]:
print("The Standerd Deviation of the Normalized Tensor is :-",tf.math.reduce_std(normalized_tensor).numpy())

The Standerd Deviation of the Normalized Tensor is :- 0.3989733


In [43]:
print("The Variance of the Normalized Tensor is :-",tf.math.reduce_variance(normalized_tensor).numpy())

The Variance of the Normalized Tensor is :- 0.15917969
